### ISSUE TITLE
(BUG): Share Post To Public

### ISSUE THREAD

**Issue by MindsGaming** [webchain-network/explorer#32]
When starting an Airdrop I have picked "Share link to public" where you are suppose to be able to share the link on any site to claim the airdrop. 

I have many subscribers saying it does not allow you to input the URL after you have set up your account.

They have showed me the post and I told them I would report the issue. They are using a site called Minds.com to post the link if that helps. 
Edit: Airdrop URL : https://www.mintme.com/token/MTCG/intro/airdrop
Thanks

**Comment by tendo-abc** [comment]
Hello, it's not connected https://github.com/mintme-com/explorer/issues/32 so please write to support@mintme.comto or any of our social media platform to answer your query in the right way
